import 'package:flutter/material.dart';

final ThemeData lightTheme = ThemeData(
  applyElevationOverlayColor: false,
  brightness: Brightness.light,
  canvasColor: const Color(0xfffff8f6),
  cardColor: const Color(0xfffff8f6),
  colorScheme: const ColorScheme(
    brightness: Brightness.light,
    error: Color(0xffba1a1a),
    errorContainer: Color(0xffffdad6),
    inversePrimary: Color(0xffffb5a0),
    inverseSurface: Color(0xff392e2b),
    onError: Color(0xffffffff),
    onErrorContainer: Color(0xff410002),
    onInverseSurface: Color(0xffffede8),
    onPrimary: Color(0xffffffff),
    onPrimaryContainer: Color(0xff3a0b01),
    onSecondary: Color(0xffffffff),
    onSecondaryContainer: Color(0xff2c150f),
    onSurface: Color(0xff231917),
    onSurfaceVariant: Color(0xff53433f),
    onTertiary: Color(0xffffffff),
    onTertiaryContainer: Color(0xff231b00),
    outline: Color(0xff85736e),
    outlineVariant: Color(0xffd8c2bc),
    primary: Color(0xff8f4c38),
    primaryContainer: Color(0xffffdbd1),
    scrim: Color(0xff000000),
    secondary: Color(0xff77574e),
    secondaryContainer: Color(0xffffdbd1),
    shadow: Color(0xff000000),
    surface: Color(0xfffff8f6),
    surfaceContainerHighest: Color(0xfff1dfda),
    surfaceTint: Color(0xff8f4c38),
    tertiary: Color(0xff6c5d2f),
    tertiaryContainer: Color(0xfff5e1a7),
  ),
  dialogBackgroundColor: const Color(0xfffff8f6),
  disabledColor: const Color(0x61610000),
  dividerColor: const Color(0x1f231917),
  focusColor: const Color(0x1f000000),
  highlightColor: const Color(0x66bcbcbc),
  hintColor: const Color(0x99000000),
  hoverColor: const Color(0x0a000000),
  iconTheme: const IconThemeData(
    color: Color(0xdd000000),
  ),
  indicatorColor: const Color(0xffffffff),
  inputDecorationTheme: const InputDecorationTheme(
    alignLabelWithHint: false,
    filled: false,
    floatingLabelAlignment: FloatingLabelAlignment.start,
    floatingLabelBehavior: FloatingLabelBehavior.auto,
    isCollapsed: false,
    isDense: false,
  ),
  materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
  platform: TargetPlatform.linux,
  primaryColor: const Color(0xff8f4c38),
  primaryColorDark: const Color(0xff1976d2),
  primaryColorLight: const Color(0xffbbdefb),
  primaryIconTheme: const IconThemeData(
    color: Color(0xffffffff),
  ),
  buttonTheme: const ButtonThemeData(
    alignedDropdown: false,
    buttonColor: Color(0xff8f4c38),
    colorScheme: ColorScheme(
      brightness: Brightness.light,
      error: Color(0xffba1a1a),
      errorContainer: Color(0xffffdad6),
      inversePrimary: Color(0xffffb5a0),
      inverseSurface: Color(0xff392e2b),
      onError: Color(0xffffffff),
      onErrorContainer: Color(0xff410002),
      onInverseSurface: Color(0xffffede8),
      onPrimary: Color(0xffffffff),
      onPrimaryContainer: Color(0xff3a0b01),
      onSecondary: Color(0xffffffff),
      onSecondaryContainer: Color(0xff2c150f),
      onSurface: Color(0xff231917),
      onSurfaceVariant: Color(0xff53433f),
      onTertiary: Color(0xffffffff),
      onTertiaryContainer: Color(0xff231b00),
      outline: Color(0xff85736e),
      outlineVariant: Color(0xffd8c2bc),
      primary: Color(0xff8f4c38),
      primaryContainer: Color(0xffffdbd1),
      scrim: Color(0xff000000),
      secondary: Color(0xff77574e),
      secondaryContainer: Color(0xffffdbd1),
      shadow: Color(0xff000000),
      surface: Color(0xfffff8f6),
      surfaceContainerHighest: Color(0xfff1dfda),
      surfaceTint: Color(0xff8f4c38),
      tertiary: Color(0xff6c5d2f),
      tertiaryContainer: Color(0xfff5e1a7),
    ),
    height: 36,
    minWidth: 88,
    padding: EdgeInsets.symmetric(horizontal: 16),
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.all(Radius.elliptical(2, 2)),
      side: BorderSide(
        color: Color(0xff000000),
        width: 0,
        style: BorderStyle.none,
      ),
    ),
    layoutBehavior: ButtonBarLayoutBehavior.padded,
  ),
);

final ThemeData darkTheme = ThemeData(
  applyElevationOverlayColor: true,
  brightness: Brightness.dark,
  canvasColor: const Color(0xff1a110f),
  cardColor: const Color(0xff1a110f),
  colorScheme: const ColorScheme(
    brightness: Brightness.dark,
    error: Color(0xffffb4ab),
    errorContainer: Color(0xff93000a),
    inversePrimary: Color(0xff8f4c38),
    inverseSurface: Color(0xfff1dfda),
    onError: Color(0xff690005),
    onErrorContainer: Color(0xffffdad6),
    onInverseSurface: Color(0xff392e2b),
    onPrimary: Color(0xff561f0f),
    onPrimaryContainer: Color(0xffffdbd1),
    onSecondary: Color(0xff442a22),
    onSecondaryContainer: Color(0xffffdbd1),
    onSurface: Color(0xfff1dfda),
    onSurfaceVariant: Color(0xffd8c2bc),
    onTertiary: Color(0xff3b2f05),
    onTertiaryContainer: Color(0xfff5e1a7),
    outline: Color(0xffa08c87),
    outlineVariant: Color(0xff53433f),
    primary: Color(0xffffb5a0),
    primaryContainer: Color(0xff723523),
    scrim: Color(0xff000000),
    secondary: Color(0xffe7bdb2),
    secondaryContainer: Color(0xff5d4037),
    shadow: Color(0xff000000),
    surface: Color(0xff1a110f),
    surfaceContainerHighest: Color(0xff3d322f),
    surfaceTint: Color(0xffffb5a0),
    tertiary: Color(0xffd8c58d),
    tertiaryContainer: Color(0xff534619),
  ),
  dialogBackgroundColor: const Color(0xff1a110f),
  disabledColor: const Color(0x62ffffff),
  dividerColor: const Color(0x1f1df1df),
  focusColor: const Color(0x1fffffff),
  highlightColor: const Color(0x40cccccc),
  hintColor: const Color(0x99ffffff),
  hoverColor: const Color(0x0affffff),
  iconTheme: const IconThemeData(
    color: Color(0xffffffff),
  ),
  indicatorColor: const Color(0xfff1dfda),
  inputDecorationTheme: const InputDecorationTheme(
    alignLabelWithHint: false,
    filled: false,
    floatingLabelAlignment: FloatingLabelAlignment.start,
    floatingLabelBehavior: FloatingLabelBehavior.auto,
    isCollapsed: false,
    isDense: false,
  ),
  materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
  platform: TargetPlatform.linux,
  primaryColor: const Color(0xff1a110f),
  primaryColorDark: const Color(0xff000000),
  primaryColorLight: const Color(0xff9e9e9e),
  primaryIconTheme: const IconThemeData(
    color: Color(0xffffffff),
  ),
  buttonTheme: const ButtonThemeData(
    alignedDropdown: false,
    buttonColor: Color(0xffffb5a0),
    colorScheme: ColorScheme(
      brightness: Brightness.dark,
      error: Color(0xffffb4ab),
      errorContainer: Color(0xff93000a),
      inversePrimary: Color(0xff8f4c38),
      inverseSurface: Color(0xfff1dfda),
      onError: Color(0xff690005),
      onErrorContainer: Color(0xffffdad6),
      onInverseSurface: Color(0xff392e2b),
      onPrimary: Color(0xff561f0f),
      onPrimaryContainer: Color(0xffffdbd1),
      onSecondary: Color(0xff442a22),
      onSecondaryContainer: Color(0xffffdbd1),
      onSurface: Color(0xfff1dfda),
      onSurfaceVariant: Color(0xffd8c2bc),
      onTertiary: Color(0xff3b2f05),
      onTertiaryContainer: Color(0xfff5e1a7),
      outline: Color(0xffa08c87),
      outlineVariant: Color(0xff53433f),
      primary: Color(0xffffb5a0),
      primaryContainer: Color(0xff723523),
      scrim: Color(0xff000000),
      secondary: Color(0xffe7bdb2),
      secondaryContainer: Color(0xff5d4037),
      shadow: Color(0xff000000),
      surface: Color(0xff1a110f),
      surfaceContainerHighest: Color(0xff3d322f),
      surfaceTint: Color(0xffffb5a0),
      tertiary: Color(0xffd8c58d),
      tertiaryContainer: Color(0xff534619),
    ),
    height: 36,
    minWidth: 88,
    padding: EdgeInsets.symmetric(horizontal: 16),
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.all(Radius.elliptical(2, 2)),
      side: BorderSide(
        color: Color(0xff000000),
        width: 0,
        style: BorderStyle.none,
      ),
    ),
    layoutBehavior: ButtonBarLayoutBehavior.padded,
  ),
);
