// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLFvnALvnnD6sd0_OoCh_2MDjlmk0PnGg',
    appId: '1:791382668395:web:5a01646da7ee414985ad2e',
    messagingSenderId: '791382668395',
    projectId: 'fireweb-5ed84',
    authDomain: 'fireweb-5ed84.firebaseapp.com',
    storageBucket: 'fireweb-5ed84.appspot.com',
    measurementId: 'G-Y4V3DND5MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM82Hz0W5UjckV7h_eDmwsrrAP-JRhgf8',
    appId: '1:791382668395:android:eb2a7e886714e6e285ad2e',
    messagingSenderId: '791382668395',
    projectId: 'fireweb-5ed84',
    storageBucket: 'fireweb-5ed84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtiI542aOe7BT52DGqB5IPy8qhmbWHT_c',
    appId: '1:791382668395:ios:826222abb95d40ec85ad2e',
    messagingSenderId: '791382668395',
    projectId: 'fireweb-5ed84',
    storageBucket: 'fireweb-5ed84.appspot.com',
    iosBundleId: 'io.nyxbit.pasabuy.pasabuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtiI542aOe7BT52DGqB5IPy8qhmbWHT_c',
    appId: '1:791382668395:ios:826222abb95d40ec85ad2e',
    messagingSenderId: '791382668395',
    projectId: 'fireweb-5ed84',
    storageBucket: 'fireweb-5ed84.appspot.com',
    iosBundleId: 'io.nyxbit.pasabuy.pasabuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLFvnALvnnD6sd0_OoCh_2MDjlmk0PnGg',
    appId: '1:791382668395:web:1b451aa267c2b9b285ad2e',
    messagingSenderId: '791382668395',
    projectId: 'fireweb-5ed84',
    authDomain: 'fireweb-5ed84.firebaseapp.com',
    storageBucket: 'fireweb-5ed84.appspot.com',
    measurementId: 'G-24MZEWQDCP',
  );
}
